export default {
    products: [
        {
            _id: '1',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 72,
            brand: 'Hiskywin',
            rating: 4.7,
            numReviews: 10,
            countInStock: 7,
        },
        {
            _id: '2',
            name: 'Free People Eloise top',
            category: 'Shirts',
            image: '/images/product-2.jpg',
            price: 88,
            brand: 'Nice',
            rating: 4.8,
            numReviews: 10,
            countInStock: 7,
        },
        {
            _id: '3',
            name: 'Free People Eloise top',
            category: 'Shirts',
            image: '/images/product-3.jpg',
            price: 128,
            brand: 'Adidas',
            rating: 3.5,
            numReviews: 10,
            countInStock: 7,
        },
        {
            _id: '4',
            name: 'Free People Eloise top',
            category: 'Shirts',
            image: '/images/product-4.jpg',
            price: 172,
            brand: 'Reebok',
            rating: 4.2,
            numReviews: 10,
            countInStock: 7,
        },
        {
            _id: '5',
            name: 'Free People Eloise top',
            category: 'Shirts',
            image: '/images/product-5.jpg',
            price: 88,
            brand: 'Puma',
            rating: 4.9,
            numReviews: 10,
            countInStock: 7,
        },
        {
            _id: '6',
            name: 'Free People Eloise top',
            category: 'Shirts',
            image: '/images/product-6.jpg',
            price: 126,
            brand: 'Salamandra',
            rating: 3.5,
            numReviews: 10,
            countInStock: 7,
        },
        {
            _id: '7',
            name: 'Free People Eloise top',
            category: 'Shirts',
            image: '/images/product-7.jpg',
            price: 196,
            brand: 'Dnipryanka',
            rating: 4.8,
            numReviews: 10,
            countInStock: 7,
        },
    ]
}